blueprint:
  name: MQTT scene state switch
  description: Automation blueprint for many z-wave switches with up/down button
    and multiple key presses. Designed with Inovelli LNSW31 and Zooz ZEN34 mappings in mind.
  source_url: https://github.com/Sunbuzz/homeassistant/blob/main/mqtt-zrc_90-blueprint.yaml
  domain: automation
  input:
    remotec_zrc90:
      name: Remotec ZRC-90
      description: The Remotec ZRC-90 to interact with.
      selector:
        device:
          integration: mqtt
          manufacturer: Remotec
          model: Scene master 8 button remote (BW8510)
    button_1_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_1_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
trigger_variables:
  device_id: !input remotec_zrc90
  device_name: device_attr(device_id,"name")
trigger:
- platform: event
  event_type: state_changed
condition: '{{ trigger.event.data.new_state.attributes.friendly_name[0:-22] == device_name }}'
action:
- variables:
    scene_id: '{{ (trigger.event.data.new_state.attributes.friendly_name[-3:]) }}'
    state_value_id: '{{ trigger.event.data.new_state.state | int  }}'
- choose:
  - conditions: '{{ scene_id == "001" and state_value_id == 0 }}'
    sequence: !input 'button_1_1'
  - conditions: '{{ scene_id == "002" and state_value_id == 2 }}'
    sequence: !input 'button_1_2'
