blueprint:
  name: MQTT ZRC-90
  description: Automation blueprint for ZRC-90 using WaveJS MQTT.
  source_url: https://github.com/Sunbuzz/homeassistant/blob/main/mqtt-zrc_90-blueprint.yaml
  domain: automation
  input:
    remotec_zrc90:
      name: Remotec ZRC-90
      description: The Remotec ZRC-90 to interact with.
      selector:
        device:
          integration: mqtt
          manufacturer: Remotec
          model: Scene master 8 button remote (BW8510)
    button_1_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_1_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_1_3:
      name: Button 1 - Hold
      description: Action to run when the button is held down.
      default: []
      selector:
        action: {}
    button_2_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_2_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_2_3:
      name: Button 1 - Hold
      description: Action to run when the button is held down.
      default: []
      selector:
        action: {}
    button_3_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_3_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_3_3:
      name: Button 1 - Hold
      description: Action to run when the button is held down.
      default: []
      selector:
        action: {}
    button_4_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_4_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_4_3:
      name: Button 1 - Hold
      description: Action to run when the button is held down.
      default: []
      selector:
        action: {}
    button_5_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_5_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_5_3:
      name: Button 1 - Hold
      description: Action to run when the button is held down.
      default: []
      selector:
        action: {}
    button_6_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_6_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_6_3:
      name: Button 1 - Hold
      description: Action to run when the button is held down.
      default: []
      selector:
        action: {}
    button_7_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_7_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_7_3:
      name: Button 1 - Hold
      description: Action to run when the button is held down.
      default: []
      selector:
        action: {}
    button_8_1:
      name: Button 1 - Single click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_8_2:
      name: Button 1 - Double click
      description: Action to run when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_8_3:
      name: Button 1 - Hold
      description: Action to run when the button is held down.
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
variables:
  device_id: !input remotec_zrc90
  device_name: '{{ device_attr(device_id,"name") }}'
trigger:
- platform: event
  event_type: state_changed
condition: '{{ trigger.event.data.new_state.attributes.friendly_name[0:-22] == device_name }}'
action:
- variables:
    scene_id: '{{ (trigger.event.data.new_state.attributes.friendly_name[-3:]) }}'
    state_value_id: '{{ trigger.event.data.new_state.state | int  }}'
- choose:
  - conditions: '{{ scene_id == "001" and state_value_id == 0 }}'
    sequence: !input 'button_1_1'
  - conditions: '{{ scene_id == "001" and state_value_id == 3 }}'
    sequence: !input 'button_1_2'
  - conditions: '{{ scene_id == "001" and state_value_id == 1 }}'
    sequence: !input 'button_1_3'
  - conditions: '{{ scene_id == "002" and state_value_id == 0 }}'
    sequence: !input 'button_2_1'
  - conditions: '{{ scene_id == "002" and state_value_id == 3 }}'
    sequence: !input 'button_2_2'
  - conditions: '{{ scene_id == "002" and state_value_id == 1 }}'
    sequence: !input 'button_2_3'
  - conditions: '{{ scene_id == "003" and state_value_id == 0 }}'
    sequence: !input 'button_3_1'
  - conditions: '{{ scene_id == "003" and state_value_id == 3 }}'
    sequence: !input 'button_3_2'
  - conditions: '{{ scene_id == "003" and state_value_id == 1 }}'
    sequence: !input 'button_3_3'
  - conditions: '{{ scene_id == "004" and state_value_id == 0 }}'
    sequence: !input 'button_4_1'
  - conditions: '{{ scene_id == "004" and state_value_id == 3 }}'
    sequence: !input 'button_4_2'
  - conditions: '{{ scene_id == "004" and state_value_id == 1 }}'
    sequence: !input 'button_4_3'
  - conditions: '{{ scene_id == "005" and state_value_id == 0 }}'
    sequence: !input 'button_5_1'
  - conditions: '{{ scene_id == "005" and state_value_id == 3 }}'
    sequence: !input 'button_5_2'
  - conditions: '{{ scene_id == "005" and state_value_id == 1 }}'
    sequence: !input 'button_5_3'
  - conditions: '{{ scene_id == "006" and state_value_id == 0 }}'
    sequence: !input 'button_6_1'
  - conditions: '{{ scene_id == "006" and state_value_id == 3 }}'
    sequence: !input 'button_6_2'
  - conditions: '{{ scene_id == "006" and state_value_id == 1 }}'
    sequence: !input 'button_6_3'
  - conditions: '{{ scene_id == "007" and state_value_id == 0 }}'
    sequence: !input 'button_7_1'
  - conditions: '{{ scene_id == "007" and state_value_id == 3 }}'
    sequence: !input 'button_7_2'
  - conditions: '{{ scene_id == "007" and state_value_id == 1 }}'
    sequence: !input 'button_7_3'
  - conditions: '{{ scene_id == "008" and state_value_id == 0 }}'
    sequence: !input 'button_8_1'
  - conditions: '{{ scene_id == "008" and state_value_id == 3 }}'
    sequence: !input 'button_8_2'
  - conditions: '{{ scene_id == "008" and state_value_id == 1 }}'
    sequence: !input 'button_8_3'
